# Generated by Django 4.1.3 on 2022-12-10 21:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Divine', '0005_activity_gallery_homedata_remove_customuser_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='date_of_event',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
