# Generated by Django 4.1.3 on 2022-12-10 21:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Divine', '0006_activity_date_of_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='date_of_event',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
