# Generated by Django 4.1.3 on 2022-12-11 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Divine', '0007_alter_activity_date_of_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='exco',
            field=models.BooleanField(default=False),
        ),
    ]
