# Generated by Django 4.1.3 on 2022-12-11 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Divine', '0008_customuser_exco'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Anonymous', max_length=30)),
                ('email', models.EmailField(default='anonymous@gmail.com', max_length=254)),
                ('title', models.CharField(max_length=30)),
                ('message', models.TextField()),
            ],
        ),
    ]
